[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/juliowernermm/"
[[redirects]]
  from = "/github"
  to = "https://github.com/julio-werner/"
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/julio-werner/"
[[redirects]]
  from = "https://juliowerner.tk/"
  to = "https://juliowerner.com/"
  status = 301
  force = true
[[redirects]]
  from = "https://juliowerner.tk/*"
  to = "https://juliowerner.com/:splat"
  status = 301
  force = true